name: shelf_cors
version: 0.3.0
author: George Moschovitis <george.moschovitis@gmail.com>
description: Middleware to add CORS headers to shelf responses.
homepage: https://github.com/gmosx/dart-shelf_cors
environment:
  sdk: ">=1.0.0 <3.0.0"
dependencies:
  shelf: any
dev_dependencies:
  test: any
